export const S = {
  wrap: { fontFamily: "'Inter', sans-serif", background: '#FAFAF8', minHeight: '100vh' },
  header: { background: '#0B6B5B', padding: '20px 20px 16px', color: '#fff' },
  headerTitle: { fontSize: 20, fontWeight: 700, margin: 0 },
  headerSub: { fontSize: 12, opacity: 0.75, marginTop: 2 },
  card: { background: '#fff', borderRadius: 16, padding: '16px', marginBottom: 12, boxShadow: '0 1px 3px rgba(0,0,0,0.06)' },
  cardTitle: { fontSize: 13, fontWeight: 600, color: '#6B7280', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 12 },
  btn: { background: '#0B6B5B', color: '#fff', border: 'none', borderRadius: 12, padding: '14px 20px', fontSize: 15, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, justifyContent: 'center', width: '100%' },
  btnOutline: { background: '#fff', color: '#0B6B5B', border: '2px solid #0B6B5B', borderRadius: 12, padding: '12px 20px', fontSize: 14, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, justifyContent: 'center', width: '100%' },
  btnSm: { background: '#E8F5F1', color: '#0B6B5B', border: 'none', borderRadius: 10, padding: '10px 16px', fontSize: 13, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6 },
  input: { width: '100%', border: '1.5px solid #E5E7EB', borderRadius: 10, padding: '11px 14px', fontSize: 14, fontFamily: 'inherit', outline: 'none', boxSizing: 'border-box', background: '#FAFAF8' },
  label: { fontSize: 13, fontWeight: 500, color: '#374151', marginBottom: 6, display: 'block' },
  nav: { position: 'fixed', bottom: 0, left: '50%', transform: 'translateX(-50%)', width: '100%', maxWidth: 430, background: '#fff', borderTop: '1px solid #E5E7EB', display: 'flex', zIndex: 100 },
  navBtn: { flex: 1, padding: '12px 0', border: 'none', background: 'none', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 3, fontSize: 10, fontWeight: 500, color: '#9CA3AF', fontFamily: 'inherit' },
  navBtnActive: { color: '#0B6B5B' },
  pill: { display: 'inline-flex', alignItems: 'center', borderRadius: 20, padding: '4px 10px', fontSize: 12, fontWeight: 500 },
  modal: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', zIndex: 200, display: 'flex', alignItems: 'flex-end', justifyContent: 'center' },
  modalBox: { background: '#fff', borderRadius: '20px 20px 0 0', width: '100%', maxWidth: 430, padding: '24px 20px', maxHeight: '90vh', overflowY: 'auto' },
  modalTitle: { fontSize: 18, fontWeight: 700, marginBottom: 20, color: '#111827' },
  row: { display: 'flex', gap: 10 },
  tag: { background: '#E8F5F1', color: '#0B6B5B', borderRadius: 8, padding: '6px 12px', fontSize: 13, fontWeight: 500, cursor: 'pointer', border: '1.5px solid transparent' },
  tagActive: { background: '#0B6B5B', color: '#fff', border: '1.5px solid #0B6B5B' },
  divider: { height: 1, background: '#F3F4F6', margin: '12px 0' },
  emptyState: { textAlign: 'center', padding: '32px 20px', color: '#9CA3AF' },
};
